import React, { useState } from 'react';
import { Check, Copy, Eye, EyeOff, Loader2, RefreshCw, UserPlus } from 'lucide-react';
import * as api from '../../api';
import { GLOBAL_ROLE_LABELS, GlobalRole } from '../../utils/permissions';

const GLOBAL_ROLES = [GlobalRole.GUEST, GlobalRole.MEMBER, GlobalRole.ADMIN];

// Matches the backend's `AdminUserCreate` minimum, so a password that is too
// short is caught here rather than as a 422 after the round trip.
const MIN_PASSWORD_LENGTH = 8;

/**
 * Generate a password worth handing over.
 *
 * Ambiguous glyphs are left out on purpose: this password is read off a screen
 * and typed by somebody else, and telling `l` from `1` or `O` from `0` in that
 * situation is a support request waiting to happen.
 */
const generatePassword = () => {
  const alphabet = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = new Uint32Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (n) => alphabet[n % alphabet.length]).join('');
};

const readableError = (err, fallback) =>
  (err?.message || '').replace(/^API Error:\s*/i, '') || fallback;

/**
 * Create an account outright.
 *
 * iquana sends no mail, so there is nowhere to deliver an activation link to:
 * the admin picks the password and hands it over out of band. The dialog is
 * built around that — the password is generated by default, shown in the clear,
 * and copyable, because it has to leave this screen by some other route.
 */
const CreateUserModal = ({ isOpen, onClose, onCreated }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState(generatePassword);
  const [globalRole, setGlobalRole] = useState(GlobalRole.MEMBER);
  const [revealed, setRevealed] = useState(true);
  const [copied, setCopied] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);

  if (!isOpen) return null;

  const reset = () => {
    setUsername('');
    setPassword(generatePassword());
    setGlobalRole(GlobalRole.MEMBER);
    setCopied(false);
    setError(null);
  };

  const handleClose = () => {
    reset();
    onClose();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(password);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access can be refused (insecure origin, browser policy). The
      // password is on screen either way, so this is not worth an error banner.
      setCopied(false);
    }
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setSaving(true);
    setError(null);
    try {
      const response = await api.createUser({
        username: username.trim(),
        password,
        global_role: globalRole,
        is_active: true,
      });
      onCreated(response.user, password);
      reset();
      onClose();
    } catch (err) {
      setError(readableError(err, 'Could not create the account.'));
    } finally {
      setSaving(false);
    }
  };

  const tooShort = password.length < MIN_PASSWORD_LENGTH;
  const disabled = saving || !username.trim() || tooShort;

  return (
    <div className="fixed inset-0 bg-scrim flex items-center justify-center z-50 p-4">
      <form
        onSubmit={handleSubmit}
        className="bg-p1 rounded-xl shadow-2xl max-w-md w-full mx-auto border border-ln"
      >
        <div className="flex items-center gap-3 p-6 border-b border-ln">
          <div className="p-2 bg-acS rounded-full">
            <UserPlus className="w-5 h-5 text-ac" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-t1">Create account</h3>
            <p className="text-sm text-t3">
              The password is handed over by you — no mail is sent.
            </p>
          </div>
        </div>

        <div className="p-6 space-y-4">
          {error && (
            <div className="p-3 bg-errBg border border-errLn rounded-lg">
              <p className="text-err text-sm">{error}</p>
            </div>
          )}

          <label className="block">
            <span className="text-sm font-medium text-t2">Username</span>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              autoFocus
              autoComplete="off"
              className="mt-1 w-full px-3 py-2 border border-ln2 rounded-lg bg-p1 text-t1 focus:ring-2 focus:ring-ac focus:outline-none"
              placeholder="e.g. participant-07"
            />
          </label>

          <div>
            <span className="text-sm font-medium text-t2">Password</span>
            <div className="mt-1 flex items-stretch gap-2">
              <input
                type={revealed ? 'text' : 'password'}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete="new-password"
                className="flex-1 min-w-0 px-3 py-2 font-mono text-sm border border-ln2 rounded-lg bg-p1 text-t1 focus:ring-2 focus:ring-ac focus:outline-none"
              />
              <button
                type="button"
                onClick={() => setRevealed((shown) => !shown)}
                title={revealed ? 'Hide' : 'Show'}
                className="px-3 bg-hv hover:bg-hv2 text-t2 hover:text-t1 rounded-lg transition-colors"
              >
                {revealed ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
              <button
                type="button"
                onClick={() => setPassword(generatePassword())}
                title="Generate a new password"
                className="px-3 bg-hv hover:bg-hv2 text-t2 hover:text-t1 rounded-lg transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
              <button
                type="button"
                onClick={handleCopy}
                title="Copy to clipboard"
                className="px-3 bg-hv hover:bg-hv2 text-t2 hover:text-t1 rounded-lg transition-colors"
              >
                {copied ? <Check className="w-4 h-4 text-ok" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
            <p className={`mt-1 text-xs ${tooShort ? 'text-err' : 'text-t3'}`}>
              {tooShort
                ? `At least ${MIN_PASSWORD_LENGTH} characters.`
                : 'Copy it before saving — it cannot be read back afterwards.'}
            </p>
          </div>

          <label className="block">
            <span className="text-sm font-medium text-t2">Platform role</span>
            <select
              value={globalRole}
              onChange={(e) => setGlobalRole(e.target.value)}
              className="mt-1 w-full px-3 py-2 border border-ln2 rounded-lg bg-p1 text-t1 focus:ring-2 focus:ring-ac focus:outline-none"
            >
              {GLOBAL_ROLES.map((role) => (
                <option key={role} value={role}>
                  {GLOBAL_ROLE_LABELS[role].label}
                </option>
              ))}
            </select>
            <p className="mt-1 text-xs text-t3">
              {GLOBAL_ROLE_LABELS[globalRole]?.description}
            </p>
          </label>
        </div>

        <div className="flex justify-end gap-2 p-6 border-t border-ln">
          <button
            type="button"
            onClick={handleClose}
            className="px-4 py-2 bg-hv hover:bg-hv2 text-t2 hover:text-t1 rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={disabled}
            className="flex items-center gap-2 px-4 py-2 bg-accent text-onAccent rounded-lg hover:brightness-110 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {saving && <Loader2 className="w-4 h-4 animate-spin" />}
            Create account
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateUserModal;
